name: Self-Hosted Runner Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted  # Используем self-hosted runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Hello World
      run: |
        echo "🎉 Работает на self-hosted runner!"
        echo "ОС: $(den -a)"
        echo "IP: $(192.168.0.112-I)"
